name: Update Timestamp

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every 10 minutes
    #- cron: '30 0 * * 3' # This runs at 00:30 UTC every Wednesday
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
        python -m pip install beautifulsoup4
        
    - name: Update timestamp
      run: python .github/scripts/generate_summary.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-actions@example.com"
        git add docs/index.html
        git commit -m "Update summary page" || echo "No changes to commit"
        git push
